apiVersion: v1
kind: Secret
metadata:
  name: pythonirc-secret
type: Opaque
stringData:
  SECRET_KEY: "supersecretkey123"
  DATABASE_URL: "postgresql+asyncpg://irc_user:irc_password@192.168.49.1:5432/irc_chat"
  REDIS_URL: "redis://192.168.49.1:6379"
  SENTRY_DSN: ""