apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secret.secretKey }}
  DATABASE_URL: {{ .Values.secret.databaseUrl }}
  REDIS_URL: {{ .Values.secret.redisUrl }}
  SENTRY_DSN: {{ .Values.secret.sentryDsn }}